In [2]:
import numpy as np

In [4]:
### TRY THESE EXERCISES FOR YOURSELF!

A = [[1, 2, 3], [4, 5, 6], [7, 8,9]]
print(np.sum(A))

print()
print()

print(np.sum(A, axis = 0))
print(np.sum(A, axis = 0).shape)

print()
print()

print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1).shape)

print()
print()

print(np.sum(A, axis = 0,keepdims = True))
print(np.sum(A, axis = 0,keepdims = True).shape)

print()
print()

print(np.sum(A, axis = 1,keepdims = True))
print(np.sum(A, axis = 1,keepdims = True).shape)

print()
print()

print(np.max(A, axis = 0))
print(np.max(A, axis = 1))

45


[12 15 18]
(3,)


[ 6 15 24]
(3,)


[[12 15 18]]
(1, 3)


[[ 6]
 [15]
 [24]]
(3, 1)


[7 8 9]
[3 6 9]
