# Homework: Build a 4-5 Layer Neural Network

## Objective
Extend your knowledge of neural networks to build a deeper network with 4-5 layers using NumPy and dot products.

## Network Architecture
- **Input Layer**: 4 features (batch of 3 samples)
- **Hidden Layer 1**: 5 neurons
- **Hidden Layer 2**: 4 neurons
- **Hidden Layer 3**: 3 neurons
- **Output Layer**: 2 neurons (for binary classification)

Total: 5 layers (1 input + 3 hidden + 1 output)

In [13]:
import numpy as np

## Step 1: Define Input Data
Create a batch of 3 input samples, each with 4 features

In [14]:
# TODO: Create input data (3 samples x 4 features)
# Hint: Use a list of lists or np.array()
inputs = np.array([
    # Add your 3 samples here
    # Each sample should have 4 features
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
])

print("Input shape:", inputs.shape)
print("Inputs:\n", inputs)

Input shape: (3, 4)
Inputs:
 [[ 1.   2.   3.   2.5]
 [ 2.   5.  -1.   2. ]
 [-1.5  2.7  3.3 -0.8]]


## Step 2: Define Weights and Biases for Layer 1
Layer 1: 4 inputs → 5 neurons

Remember: weights shape should be (num_neurons, num_inputs)

In [15]:
# TODO: Initialize weights for layer 1 (5 neurons x 4 inputs)
# You can use random values between -1 and 1
weights1 = np.array([
    # 5 rows (neurons), 4 columns (inputs)
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
    [0.72, 0.88, -0.15, 0.31],
    [-0.25, -0.67, 0.13, 0.24]
])

# TODO: Initialize biases for layer 1 (5 neurons)
biases1 = np.array([1,2,3,4,5])  # 5 values

print("Weights1 shape:", weights1.shape)
print("Biases1 shape:", biases1.shape)

Weights1 shape: (5, 4)
Biases1 shape: (5,)


## Step 3: Define Weights and Biases for Layer 2
Layer 2: 5 inputs (from layer 1) → 4 neurons

In [16]:
# TODO: Initialize weights for layer 2 (4 neurons x 5 inputs)
weights2 = np.array([
    [0.1, -0.14, 0.5, 0.1, -0.14],
    [-0.5, 0.12, -0.33, -0.5, 0.12],
    [-0.44, 0.73, -0.13, -0.44, 0.73],
    [0.81, -0.31, -0.38, 0.81, -0.31]
])

# TODO: Initialize biases for layer 2
biases2 = np.array([-1,2,-0.5,1])  # 4 values

print("Weights2 shape:", weights2.shape)
print("Biases2 shape:", biases2.shape)

Weights2 shape: (4, 5)
Biases2 shape: (4,)


## Step 4: Define Weights and Biases for Layer 3
Layer 3: 4 inputs (from layer 2) → 3 neurons

In [17]:
# TODO: Initialize weights for layer 3 (3 neurons x 4 inputs)
weights3 = np.array([
    [0.1, -0.14, 0.5, 0.1],
    [-0.5, 0.12, -0.33, -0.5],
    [-0.44, 0.73, -0.13, -0.44]
])

# TODO: Initialize biases for layer 3
biases3 = np.array([-1,2,3])  # 3 values

print("Weights3 shape:", weights3.shape)
print("Biases3 shape:", biases3.shape)

Weights3 shape: (3, 4)
Biases3 shape: (3,)


## Step 5: Define Weights and Biases for Output Layer (Layer 4)
Layer 4: 3 inputs (from layer 3) → 2 neurons (output)

In [18]:
# TODO: Initialize weights for output layer (2 neurons x 3 inputs)
weights4 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33]
])

# TODO: Initialize biases for output layer
biases4 = np.array([-1,2])  # 2 values

print("Weights4 shape:", weights4.shape)
print("Biases4 shape:", biases4.shape)

Weights4 shape: (2, 3)
Biases4 shape: (2,)


## Step 6: Forward Pass - Calculate Layer 1 Output
Use the dot product formula you learned: `output = np.dot(inputs, weights.T) + biases`

In [19]:
# TODO: Calculate layer 1 outputs
layer1_outputs = np.dot(inputs, weights1.T) + biases1

print("Layer 1 outputs shape:", layer1_outputs.shape)
print("Layer 1 outputs:\n", layer1_outputs)

Layer 1 outputs shape: (3, 5)
Layer 1 outputs:
 [[ 3.8    0.21   4.885  6.805  4.4  ]
 [ 7.9   -2.81   2.7   10.61   1.5  ]
 [ 0.41   0.051  2.526  4.553  3.803]]


## Step 7: Forward Pass - Calculate Layer 2 Output

In [20]:
# TODO: Calculate layer 2 outputs (use layer1_outputs as input)
layer2_outputs = np.dot(layer1_outputs, weights2.T) + biases2

print("Layer 2 outputs shape:", layer2_outputs.shape)
print("Layer 2 outputs:\n", layer2_outputs)

Layer 2 outputs shape: (3, 4)
Layer 2 outputs:
 [[ 1.8576  -4.36135 -2.43595  6.30465]
 [ 2.3844  -8.3032  -9.9517  15.3732 ]
 [ 0.21974 -0.8526  -0.19868  2.86541]]


## Step 8: Forward Pass - Calculate Layer 3 Output

In [21]:
# TODO: Calculate layer 3 outputs (use layer2_outputs as input)
layer3_outputs = np.dot(layer2_outputs, weights3.T) + biases3

print("Layer 3 outputs shape:", layer3_outputs.shape)
print("Layer 3 outputs:\n", layer3_outputs)

Layer 3 outputs shape: (3, 3)
Layer 3 outputs:
 [[-0.791161  -1.8006235 -3.458502 ]
 [-3.037642  -4.591123  -9.580959 ]
 [-0.671461   0.4206774  1.0459644]]


## Step 9: Forward Pass - Calculate Final Output

In [22]:
# TODO: Calculate final layer outputs (use layer3_outputs as input)
final_outputs = np.dot(layer3_outputs, weights4.T) + biases4

print("Final outputs shape:", final_outputs.shape)
print("Final outputs:\n", final_outputs)

Final outputs shape: (3, 2)
Final outputs:
 [[-2.55627981  3.32081134]
 [-5.45148648  6.12960271]
 [-0.60305874  2.04104354]]


## Step 10: Bonus Challenge - Complete Forward Pass in One Cell
Rewrite all the forward pass calculations in a single code cell

In [23]:
# TODO: Complete forward pass from inputs to final outputs
# Hint: Chain the calculations together

# Layer 1
layer1_outputs = np.dot(inputs, weights1.T) + biases1

# Layer 2
layer2_outputs = np.dot(layer1_outputs, weights2.T) + biases2

# Layer 3
layer3_outputs = np.dot(layer2_outputs, weights3.T) + biases3

# Layer 4 (Output)
final_outputs = np.dot(layer3_outputs, weights4.T) + biases4

print("Final network output:\n", final_outputs)

Final network output:
 [[-2.55627981  3.32081134]
 [-5.45148648  6.12960271]
 [-0.60305874  2.04104354]]


## Step 11: Extra Credit - Verify Shapes
Write a function that checks if all your weight matrices and biases have the correct shapes

In [24]:
def verify_network_shapes(inputs, weights_list, biases_list):
    """
    Verify that all layers have compatible shapes
    
    Parameters:
    - inputs: input data
    - weights_list: list of weight matrices [weights1, weights2, ...]
    - biases_list: list of bias vectors [biases1, biases2, ...]
    """
    print("=" * 60)
    print("NETWORK SHAPE VERIFICATION")
    print("=" * 60)
    
    # Check input shape
    print(f"\nInput shape: {inputs.shape}")
    print(f"  - Batch size: {inputs.shape[0]}")
    print(f"  - Input features: {inputs.shape[1]}")
    
    # Track the current layer's output size (starts with input features)
    current_output_size = inputs.shape[1]
    
    # Verify each layer
    all_valid = True
    for i, (weights, biases) in enumerate(zip(weights_list, biases_list), 1):
        print(f"\n--- Layer {i} ---")
        print(f"Weights shape: {weights.shape}")
        print(f"Biases shape: {biases.shape}")
        
        # Expected: weights should be (num_neurons, num_inputs_to_this_layer)
        num_neurons = weights.shape[0]
        num_inputs = weights.shape[1]
        
        # Check 1: Does the input size match the previous layer's output?
        if num_inputs != current_output_size:
            print(f"  ❌ ERROR: Layer {i} expects {num_inputs} inputs, but previous layer outputs {current_output_size}")
            all_valid = False
        else:
            print(f"  ✓ Input size matches: {num_inputs}")
        
        # Check 2: Do biases match the number of neurons?
        if biases.shape[0] != num_neurons:
            print(f"  ❌ ERROR: Layer {i} has {num_neurons} neurons but {biases.shape[0]} biases")
            all_valid = False
        else:
            print(f"  ✓ Biases match neurons: {num_neurons}")
        
        # Check 3: Are biases 1-dimensional?
        if len(biases.shape) != 1:
            print(f"  ❌ ERROR: Biases should be 1D, but got shape {biases.shape}")
            all_valid = False
        
        # Update current output size for next layer
        current_output_size = num_neurons
        print(f"  → Output size: {current_output_size}")
    
    print("\n" + "=" * 60)
    if all_valid:
        print("✓ ALL SHAPES ARE VALID!")
        print(f"Final output: {current_output_size} neurons")
    else:
        print("❌ SHAPE ERRORS DETECTED - Please fix the issues above")
    print("=" * 60)
    
    return all_valid

# Test your function
verify_network_shapes(inputs, [weights1, weights2, weights3, weights4], [biases1, biases2, biases3, biases4])

NETWORK SHAPE VERIFICATION

Input shape: (3, 4)
  - Batch size: 3
  - Input features: 4

--- Layer 1 ---
Weights shape: (5, 4)
Biases shape: (5,)
  ✓ Input size matches: 4
  ✓ Biases match neurons: 5
  → Output size: 5

--- Layer 2 ---
Weights shape: (4, 5)
Biases shape: (4,)
  ✓ Input size matches: 5
  ✓ Biases match neurons: 4
  → Output size: 4

--- Layer 3 ---
Weights shape: (3, 4)
Biases shape: (3,)
  ✓ Input size matches: 4
  ✓ Biases match neurons: 3
  → Output size: 3

--- Layer 4 ---
Weights shape: (2, 3)
Biases shape: (2,)
  ✓ Input size matches: 3
  ✓ Biases match neurons: 2
  → Output size: 2

✓ ALL SHAPES ARE VALID!
Final output: 2 neurons


True

## Reflection Questions
Answer these questions after completing the homework:

1. What is the total number of parameters (weights + biases) in your network?
2. How does the output shape change as data flows through each layer?
3. What would happen if you swapped the order of layers 2 and 3?
4. Why do we use `weights.T` (transpose) in the dot product?

## Your Answers
Write your answers here:

1. Total parameters: ___
2. Output shape changes: ___
3. Swapping layers: ___
4. Transpose reason: ___